import CampaignList from "@/components/campaignList/CampaignList";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Campaigns",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full px-8 h-[100px] bg-[#333] z-40 fixed left-0 top-0 flex justify-between items-center">
          <Link href="/" className="text-xl text-white font-semibold">
            Home
          </Link>
          <div className="w-10 h-10 border rounded-full flex justify-center items-center text-white">
            NO
          </div>
        </div>
        <div className="w-[25%]">
          <CampaignList />
        </div>
        <div className="w-[75%] ml-[25%]">{children}</div>
      </body>
    </html>
  );
}
